language: C

sudo: true

install:
  - wget -O gawk.tar.gz https://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.gz
  - tar xzf gawk.tar.gz
  - cd gawk-5.1.0
  - ./configure; sudo make; sudo make install
  - cd ..

script:
  - chmod +x *.auk auk
  - ./tests.auk | awk '/FAIL/ {n++} END {exit n==1}'
